
EPS.Title=Sélecteur de modèle de joueur amélioré %s, Édition de Fesiug

# Main Buttons
EPS.Reset=Réinitialiser
EPS.ApplyPM=Appliquer le modèle de joueur
EPS.VisitAddonPage=Visiter la page d'extension

EPS.Search=Rechercher:

# Model Sheet
EPS.Model=Modèle
EPS.Model.Icons=Icônes
EPS.Model.Table=Table
EPS.Model.Table.Model=Modèle
EPS.Model.Table.Path=Chemin

# Hands Sheet
EPS.Hands=Mains
EPS.Hands.Icons=Icônes
EPS.Hands.Table=Table
EPS.Hands.Table.Model=Modèle
EPS.Hands.Table.Path=Chemin
EPS.Hands.UsePM=Utiliser le modèle de joueur

# Favorites Sheet
EPS.Favorites=Favoris
EPS.Favorites.Model=Modèle
EPS.Favorites.Skin=Peau
EPS.Favorites.Bodygroups=Groupes de corps
EPS.Favorites.LoadFavorite=Charger les favoris sélectionnés
EPS.Favorites.Desc=Ici, vous pouvez sauvegarder vos combinaisons des modèles de joueur préférées. Pour ce faire:\n1. Sélectionnez un modèle et configurez la peau et les groupes de corps comme vous le souhaitez.\n2. Entrez un nom unique dans le champ de texte et cliquez sur « Ajouter un nouveau favori ».\n3. Chargez votre favori en le sélectionnant dans la liste ci-dessous et en cliquant sur « Charger la sélection ».\nVous pouvez également appliquer les favoris existants via une commande console:\nplayermodel_loadfav "le nom du favori"
EPS.Favorites.AddNewFavorite=Ajouter un nouveau favori
EPS.Favorites.ReplaceSelected=Charger la sélection
EPS.Favorites.DeleteAllSelected=Supprimer tout ce qui est sélectionné

# Bodygroups Sheet
EPS.Bodygroups=Groupes du corps

EPS.Handgroups=Groupes des mains

EPS.Skin=Peau

EPS.Flexes=Flexes
EPS.Flexes.Notes=Notes:\n-L'aperçu du modèle pour les flexes ne fonctionne pas correctement. Cependant, ils seront visibles sur votre modèle de joueur lorsque vous les appliquerez.\n- Les valeurs par défaut fournies pourraient être incorrectes et provoquer des visages déformés.\n- Il n'y a aucun moyen de réinitialiser (ou de réparer) la manipulation de flex à part débrancher.

# Colors Sheet
EPS.Colors=Couleurs
EPS.Colors.PlayerColor=Couleur du joueur
EPS.Colors.PhysgunColor=Couleur du pistolet physique
EPS.Colors.ResetToDefault=Réinitialiser aux valeurs par défaut

# Settings Sheet
EPS.Settings=Paramètres
EPS.Settings.Client=Client
EPS.Settings.Client.EnforcePM=Appliquez votre modèle de joueur
EPS.Settings.Client.EnforcePM.Desc=Si activé, le modèle de joueur que vous avez sélectionné sera protégé. Aucune autre fonction ne pourra plus modifier votre modèle de joueur.
EPS.Settings.Client.PlayerColorBG=Utiliser la couleur du joueur comme arrière-plan
EPS.Settings.Client.PlayerColorBG.Desc=Si activé, la couleur de joueur que vous avez choisie sera utilisée comme fond du menu. Si désactivé, le fond sera gris.
EPS.Settings.Client.TransparentBG=Fond transparent
EPS.Settings.Client.TransparentBG.Desc=Si activé, le fond du menu sera transparent. Si désactivé, le fond sera opaque.
EPS.Settings.Client.ShowFlexes=Afficher l’onglet Flexes
EPS.Settings.Client.ShowFlexes.Desc=Cela vous permet de manipuler les flexions sur votre modèle de joueur. Cependant, la manipulation des flexions n'est pas vraiment conçue pour les modèles de joueur et peut causer des problèmes. Cela inclut les éléments suivants:\n- Le clignement des yeux ne fonctionne plus.\n- Les visages pourraient être déformés à moins que les flexions ne soient corrigées manuellement.\n- Pourrait complètement casser les visages des modèles de personnages incompatibles.\n- Même si vous remettez tous les flexibles à leur valeur par défaut, le moteur les considère toujours comme manipulés. Les modèles avec des problèmes ne seront pas corrigés.\nVous devez changer de modèle une fois pour que l'onglet apparaisse !
EPS.Settings.Client.RebuildIcon=Reconstruire les icônes d'apparition
EPS.Settings.Client.RebuildIcon.Desc=Force tous les icônes des modèles de joueur à être re-rendus. Utile si les icônes sont dépassées après que les modèles personnalisés ont changé d'apparence. Cela peut prendre un certain temps, selon le nombre de modèles et la vitesse de votre PC.

EPS.Settings.Server=Serveur
EPS.Settings.Server.EnablePMEnforcement=Activer l'application du modèle de joueur
EPS.Settings.Server.EnablePMEnforcement.Desc=Si activé, les modèles de joueur sélectionnés seront appliqués et protégés. Aucun mode de jeu, carte ou addon ne pourra plus les remplacer. Les joueurs peuvent activer ou désactiver cette fonction individuellement en utilisant la case à cocher en haut du menu.\nSi désactivé, seul le bouton manuel fonctionne en dehors du Sandbox.
EPS.Settings.Server.AllowInstantChanges=Autoriser des changements instantanés
EPS.Settings.Server.AllowInstantChanges.Desc=Si activée, les joueurs peuvent appliquer leurs modifications instantanément au lieu de devoir réapparaître.
EPS.Settings.Server.AllowFlexes=Autoriser les joueurs de changer de flexes
EPS.Settings.Server.AllowFlexes.Desc=Si activé, les joueurs peuvent modifier les flexions de leurs modèles de personnage. Cela perturbera le clignement des yeux des joueurs et pourrait causer d'autres problèmes. À activer à vos risques et périls. Les joueurs ne peuvent réinitialiser leurs flexions qu'en se déconnectant.
EPS.Settings.Server.EnableInAllGM=Activer dans tous les modes de jeu
EPS.Settings.Server.EnableInAllGM.Desc=Si activé, le Sélecteur de Modèle de Joueur sera disponible pour tous les joueurs dans tous les modes de jeu. Si désactivé, seuls les administrateurs peuvent l'utiliser en dehors du mode Bac à sable.
EPS.Settings.Server.RequestLimit=Limite de requêtes
EPS.Settings.Server.RequestLimit.Desc=Délai en secondes que les joueurs doivent attendre avant de pouvoir utiliser à nouveau la fonction de changement instantané. Réglez sur 0 pour désactiver.

EPS.Settings.GM_Blacklist=Liste noire MDJ
EPS.Settings.GM_Blacklist.ExistedGM=Modes de jeu sur liste noire
EPS.Settings.GM_Blacklist.Desc=Ici, vous pouvez mettre sur liste noire les modes de jeu incompatibles.\n\nPlayers (including Admins) can't change their playermodels in those gamemodes, regardless of other settings.
EPS.Settings.GM_Blacklist.AddCurrent=Ajouter le mode de jeu actuel à la liste noire
EPS.Settings.GM_Blacklist.ManuallyAddGM=Ajouter manuellement le mode de jeu
EPS.Settings.GM_Blacklist.RemoveSelected=Supprimer les modes de jeu sélectionnés

EPS.Settings.VOX=VOX
EPS.Settings.VOX.PlayerModel=Modèle de joueur
EPS.Settings.VOX.Assigned=Pack VOX attribué
EPS.Settings.VOX.AvailableVOX=Pack VOX disponible
EPS.Settings.VOX.AssignToCurrent=Attribuer le pack VOX au modèle du joueur actuel
EPS.Settings.VOX.RemoveSelected=Supprimer l'affectation sélectionnée

EPS.Settings.Info=Information